name: Flask CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1) 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Docker 이미지 빌드
      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag flask-app:ci \
            .
      # 3) 컨테이너에서 테스트 실행
      - name: Run tests inside Docker
        run: |
          docker run --rm \
            flask-app:ci \
            pytest
